# 函数最小化示例的配置
max_iterations: 100
checkpoint_interval: 10
log_level: "INFO"

# LLM配置
llm:
  # primary_model: "gemini-2.0-flash-lite"
  primary_model: "llama3.1-8b"
  primary_model_weight: 0.8
  # secondary_model: "gemini-2.0-flash"
  secondary_model: "llama-4-scout-17b-16e-instruct"
  secondary_model_weight: 0.2
  # api_base: "https://generativelanguage.googleapis.com/v1beta/openai/"
  api_base: "https://api.cerebras.ai/v1"
  temperature: 0.7
  top_p: 0.95
  max_tokens: 4096

# 提示配置
prompt:
  system_message: |
    你是一位专门研究优化算法的专家程序员.
    你的任务是改进一个函数最小化算法,
    以找到一个具有许多局部最小值的复杂函数的全局最小值.
    该函数是 f(x, y) = sin(x) * cos(y) + sin(x*y) + (x^2 + y^2)/20.
    重点改进 search_algorithm 函数,
    使其能够可靠地找到全局最小值,
    避免简单算法可能陷入的局部最小值.
  num_top_programs: 3
  use_template_stochasticity: true

# 数据库配置
database:
  population_size: 50
  archive_size: 20
  num_islands: 3
  elite_selection_ratio: 0.2
  exploitation_ratio: 0.7

# 评估器配置
evaluator:
  timeout: 60
  cascade_evaluation: true
  cascade_thresholds: [0.5, 0.75]
  parallel_evaluations: 4
  use_llm_feedback: false

# 进化设置
diff_based_evolution: true
allow_full_rewrites: false
